"""
PistonCore compiler.

Takes a Piston model and produces native HA files.
  Simple piston  → HA automation YAML
  Complex piston → PyScript .py

Complexity is auto-detected — the user never chooses.
See Design Doc §3 for what makes a piston "complex".
"""

from dataclasses import dataclass, field
from typing import Literal
import re

from models.piston import Piston, ActionType


@dataclass
class CompileResult:
    target: Literal["yaml", "pyscript"]
    output: str
    filename: str
    warnings: list[str] = field(default_factory=list)


def is_complex(piston: Piston) -> bool:
    """
    Determine whether a piston needs PyScript (complex) or YAML (simple).
    Returns True if any "complex" feature is used.
    """
    # Variables → complex
    if piston.variables:
        return True

    # Scan actions recursively for complex action types
    complex_types = {
        ActionType.wait_for_state,
        ActionType.repeat,
        ActionType.call_piston,
        ActionType.set_variable,
    }
    return _actions_have_complex(piston.actions, complex_types)


def _actions_have_complex(actions, complex_types) -> bool:
    for action in actions:
        if action.type in complex_types:
            return True
        # Recurse into if/then/else branches
        for branch in [action.then_actions or [], action.else_actions or [], action.loop_actions or []]:
            if _actions_have_complex(branch, complex_types):
                return True
    return False


def safe_filename(name: str) -> str:
    """Convert a piston name to a safe filename (no spaces or special chars)."""
    slug = re.sub(r"[^\w\s-]", "", name.lower())
    slug = re.sub(r"[\s_-]+", "_", slug).strip("_")
    return slug


def compile_piston(piston: Piston) -> CompileResult:
    complex_piston = is_complex(piston)
    if complex_piston:
        return _compile_pyscript(piston)
    else:
        return _compile_yaml(piston)


def _compile_yaml(piston: Piston) -> CompileResult:
    """Compile a simple piston to HA automation YAML."""
    warnings = []
    filename = f"{safe_filename(piston.name)}.yaml"
    lines = []

    lines.append(f"# PistonCore — {piston.name}")
    lines.append(f"# Generated by PistonCore. Do not edit manually — changes will be overwritten on next deploy.")
    lines.append(f"# Piston ID: {piston.id}")
    lines.append("")
    lines.append(f"alias: \"{piston.name}\"")
    if piston.description:
        lines.append(f"description: \"{piston.description}\"")
    lines.append(f"mode: {piston.mode.value}")
    lines.append("")

    # Triggers
    lines.append("triggers:")
    if not piston.triggers:
        warnings.append("This piston has no triggers — it will never run automatically.")
        lines.append("  []")
    else:
        for trigger in piston.triggers:
            lines.extend(_yaml_trigger(trigger, piston))
    lines.append("")

    # Conditions
    if piston.conditions:
        lines.append("conditions:")
        for cond in piston.conditions:
            lines.extend(_yaml_condition(cond, piston))
        lines.append("")

    # Actions
    lines.append("actions:")
    if not piston.actions:
        warnings.append("This piston has no actions.")
        lines.append("  []")
    else:
        for action in piston.actions:
            lines.extend(_yaml_action(action, piston, indent=2))

    output = "\n".join(lines)
    return CompileResult(target="yaml", output=output, filename=filename, warnings=warnings)


def _yaml_trigger(trigger, piston: Piston) -> list[str]:
    lines = []
    role = trigger.target_role
    entity_id = piston.device_map.get(role, f"UNMAPPED_ROLE_{role}") if role else None

    if trigger.type.value == "state":
        lines.append(f"  - trigger: state")
        if entity_id:
            lines.append(f"    entity_id: {entity_id}")
        if trigger.to_state:
            lines.append(f"    to: \"{trigger.to_state}\"")
        if trigger.from_state:
            lines.append(f"    from: \"{trigger.from_state}\"")

    elif trigger.type.value == "sun":
        lines.append(f"  - trigger: sun")
        lines.append(f"    event: {trigger.event}")
        if trigger.offset_minutes:
            minutes = trigger.offset_minutes
            sign = "-" if minutes < 0 else "+"
            lines.append(f"    offset: \"{sign}{abs(minutes):02d}:00:00\"")

    elif trigger.type.value == "time":
        lines.append(f"  - trigger: time")
        lines.append(f"    at: \"{trigger.time}\"")

    elif trigger.type.value == "time_pattern":
        lines.append(f"  - trigger: time_pattern")
        if trigger.every_minutes:
            lines.append(f"    minutes: \"/{trigger.every_minutes}\"")
        elif trigger.every_hours:
            lines.append(f"    hours: \"/{trigger.every_hours}\"")

    else:
        lines.append(f"  - trigger: event")
        lines.append(f"    event_type: pistoncore_{trigger.type.value}")

    return lines


def _yaml_condition(cond, piston: Piston) -> list[str]:
    # Basic state condition — expand in future iterations
    lines = []
    role = cond.target_role
    entity_id = piston.device_map.get(role, f"UNMAPPED_{role}") if role else None

    if cond.operator.value in ("is on", "is off"):
        state = "on" if cond.operator.value == "is on" else "off"
        lines.append(f"  - condition: state")
        if entity_id:
            lines.append(f"    entity_id: {entity_id}")
        lines.append(f"    state: \"{state}\"")
    else:
        lines.append(f"  - condition: template")
        lines.append(f"    value_template: \"{{{{ true }}}}\"  # TODO: complex condition")

    return lines


def _yaml_action(action, piston: Piston, indent: int = 2) -> list[str]:
    pad = " " * indent
    lines = []
    role = action.target_role
    entity_id = piston.device_map.get(role, f"UNMAPPED_ROLE_{role}") if role else None

    if action.type == ActionType.call_service:
        lines.append(f"{pad}- action: {action.service}")
        if entity_id:
            lines.append(f"{pad}  target:")
            lines.append(f"{pad}    entity_id: {entity_id}")
        if action.data:
            lines.append(f"{pad}  data:")
            for k, v in action.data.items():
                lines.append(f"{pad}    {k}: {v}")

    elif action.type == ActionType.wait:
        if action.until:
            lines.append(f"{pad}- wait_template: \"{{{{ now().strftime('%H:%M:%S') == '{action.until}' }}}}\"")
        elif action.duration_seconds:
            mins, secs = divmod(action.duration_seconds, 60)
            hours, mins = divmod(mins, 60)
            lines.append(f"{pad}- delay: \"{hours:02d}:{mins:02d}:{secs:02d}\"")

    elif action.type == ActionType.if_then:
        lines.append(f"{pad}- if:")
        for cond in (action.conditions or []):
            lines.extend(_yaml_condition(cond, piston))
        lines.append(f"{pad}  then:")
        for sub in (action.then_actions or []):
            lines.extend(_yaml_action(sub, piston, indent + 4))
        if action.else_actions:
            lines.append(f"{pad}  else:")
            for sub in action.else_actions:
                lines.extend(_yaml_action(sub, piston, indent + 4))

    elif action.type == ActionType.log:
        lines.append(f"{pad}- action: system_log.write")
        lines.append(f"{pad}  data:")
        lines.append(f"{pad}    message: \"{action.message}\"")
        lines.append(f"{pad}    level: info")

    elif action.type == ActionType.stop:
        lines.append(f"{pad}- stop: \"Piston stopped\"")

    return lines


def _compile_pyscript(piston: Piston) -> CompileResult:
    """
    Stub for PyScript compilation.
    Full implementation in next development session.
    """
    filename = f"{safe_filename(piston.name)}.py"
    output = f"""# PistonCore — {piston.name}
# Generated by PistonCore. Do not edit manually.
# Piston ID: {piston.id}
# Target: PyScript (complex piston)
#
# Full PyScript compilation coming in the next development session.
# This piston uses features that require PyScript:
#   - Variables: {bool(piston.variables)}
#   - Advanced actions detected

@state_trigger("pistoncore.placeholder")
def piston_{safe_filename(piston.name)}(**kwargs):
    pass  # TODO: compile full piston logic
"""
    return CompileResult(
        target="pyscript",
        output=output,
        filename=filename,
        warnings=["PyScript compilation is not yet complete. Full support coming next session."],
    )
